# Generated by Django 4.2.4 on 2023-09-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Flooring Installation', 'Flooring Installation'), ('Roof Repair', 'Roof Repair'), ('Interior Renovation', 'Interior Renovation'), ('Exterior Painting', 'Exterior Painting'), ('Plumbing Installation', 'Plumbing Installation'), ('Electrical Rewiring', 'Electrical Rewiring'), ('Landscaping Design', 'Landscaping Design'), ('Kitchen Remodeling', 'Kitchen Remodeling')], max_length=100)),
                ('project_description', models.TextField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('expected_completion_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='core.customer')),
            ],
        ),
    ]
