# Generated by Django 4.2.4 on 2023-09-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_completed',
        ),
    ]
