# Generated by Django 4.2.4 on 2023-09-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_service_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
